---
- name: Deploy Artifact to Localhost
  hosts: localhost
  become: true
  become_user: nanda_123
  become_method: su

  tasks:
    - name: Copy the artifact to the target location
      copy:
        src: "/var/lib/jenkins/workspace/exp7/target/hello-maven-1.0-SNAPSHOT.jar"
        dest: "/home/nanda_123/t.jar"
