---
- name: Deploy Artifact to Localhost
  hosts: localhost
  become: true
  become_user: student-devops
  become_method: su

  tasks:
    - name: Copy the artifact to the target location
      copy:
        src: "/var/lib/jenkins/workspace/maven/target/hello-maven-1.0-SNAPSHOT.jar"
        dest: "/home/student-devops/Desktop/t.jar"
